
.SILENT:

.PHONY: cpus errors warnings

all: bugfixes cpus errors warnings

bugfixes:
	echo "Testing bugfixes..."
	echo
	make -C bugfixes

cpus:
	echo "Testing CPUs..."
	echo
	make -C cpus

errors:
	echo "Testing errors..."
	echo
	make -C errors

warnings:
	echo "Testing warnings..."
	echo
	make -C warnings
